### ISSUE TITLE
FatalError while log

### ISSUE THREAD

**Issue by aathik7** [theriddleofenigma/laravel-google-chat-log#10]
**Error Description**

I have installed the package using composer and then added config in logging and the URL in env. php and then while any error throws then the error must be logged in the chat but here I found an exception like the one below. 

`Declaration of Enigma\GoogleChatHandler::write($record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): void`

**Note: This is happened in the lumen**.

> Symfony\Component\ErrorHandler\Error\
> FatalError
> Show exception properties
> Symfony\Component\ErrorHandler\Error\FatalError {#111 ▼
>   -error: array:4 [▼
>     "type" => 64
>     "message" => "Declaration of Enigma\GoogleChatHandler::write($record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(Monolog\LogRecord $record): voi ▶"
>     "file" => "/var/www/vendor/theriddleofenigma/laravel-google-chat-log/src/GoogleChatHandler.php"
>     "line" => 19
>   ]
> }

**Comment by theriddleofenigma** [comment]
Thanks for reporting @aathik7 🙏

We have released a new version with the fix and some improvements in the log message. 🚀

Release v1.2, https://github.com/theriddleofenigma/laravel-google-chat-log/releases/tag/v1.2.0

**Comment by aathik7** [comment]
It worked! thanks, @theriddleofenigma

**Comment by anoviel** [comment]
I am getting the same error in Version 1.3
Works like a charm in 1.2
