### ISSUE TITLE
Can a space be notified instead of a person? 

### ISSUE THREAD

**Issue by chuckienorton** [theriddleofenigma/laravel-google-chat-log#9]
Hello, 

is it possible to notify a space instead of a human? For example - we have a few Dev spaces our IT/Dev team uses for automated server stuff. 

The ID (when inspecting our space icons) looks like data-group-id="space/XXXXXXXX"

Thanks in advance!

**Comment by theriddleofenigma** [comment]
@chuckienorton Google chat doesn't provide support for notifying space. Instead now you can notify multiple spaces by adding those webhook urls as comma separated in the env with the latest release. 

Thank you!
